### ISSUE TITLE
excuse me

### ISSUE THREAD

**Issue by xinkeng0** [zjengjie/SpringSessionLogoutIssue#1]
Sorry to bother you。
Can you give me your contact？
Email？WeChat？Any other。。
I want to learn the art of spring with your help。
I'm sorry that my English is so bad。

**Comment by zjengjie** [comment]
我可以说中文，spring 我现在也是处于学习中的状态，可能并不能帮到你太多。我的邮箱是这个 ID 的 Gmail。
